@tarun/feature/typography button and vitest
TarunKumardev/ecommerceapp pull request #3
Opened 2023-07-22 05:09 UTC by TarunKumardev

created two components button and typography and added configuration for testing library

2023-07-22 10:59 UTC, Sahara24 commented
Going forward make separate commits for each feature that you work, dont push all the features in one commit

2023-07-22 11:47 UTC, Sahara24 requested changes
For button component add types, I mostly see black and white button with hover, take a look at it and make similar to those buttons, and I have added some comments look into it.

2023-07-22 11:47 UTC, Sahara24 commented on src/stories/button/button.stories.tsx
> +};
Show all the variants that are there in the component, not only contained.

2023-07-22 11:47 UTC, Sahara24 commented on src/stories/button/index.tsx
> +      disabled={loading}
Do we have to disable a button with loading, what if we want to show a loader inside a button ? Isn't it good to separate both?

2023-07-22 11:47 UTC, Sahara24 commented on src/stories/typography/typography.stories.tsx
> +};
write stories for all the types available

2023-07-22 11:47 UTC, Sahara24 commented on src/stories/button/index.tsx
> +}: IButton): ReactNode {
Add hover effect also for button and make button similar to the UI in nike website

2023-07-22 11:59 UTC, TarunKumardev commented on src/stories/button/button.stories.tsx
> +};
@Sahara24  planning to create color schema component doing r&d on it  after completion of that component will integrate the colors

2023-07-22 14:42 UTC, Sahara24 approved these changes

2023-07-23 12:36 UTC, amarnathbarpanda approved these changes

2023-07-23 12:37 UTC, merged